### PR TITLE
grab api key from APPSEMBLER_FEATURES in server-vars.yml

### PR DESCRIPTION
**Pull request by tkeemon**
Pretty self-explanatory. Grabbing api key from APPSEMBLER_FEATURES, which is loaded into django.conf.settings via server-vars.yml.

@mbifulco let me know if you have any questions.

### CODE REVIEW

**Comment by mbifulco** [comment]
Hmm... my only concern is getting this running locally. Do you have an updated version of the ansible script and server-vars file that I can use with this?

**Comment by tkeemon** [comment]
Sure thing. I'll get those changes to you in just a bit.

**Comment by tkeemon** [comment]
These are the only changes you need to incorporate into Ansible in order to get accredible_certificates running in devstack:
https://github.com/appsembler/configuration/blob/appsembler/feature/mergeBirch.1/playbooks/roles/edxapp/defaults/main.yml#L19-L21
https://github.com/appsembler/configuration/blob/appsembler/feature/mergeBirch.1/playbooks/roles/edxapp/defaults/main.yml#L684

The best way to get this running locally would probably be to user our fork of the configuration repo.

``` bash
git remote add appsembler https://github.com/appsembler/configuration.git
git fetch
git checkout  appsembler/feature/mergeBirch.1
```

Then in /edx/app/edx_ansible/server-vars.yml, add:

```
EDXAPP_APPSEMBLER_FEATURES:
  ACCREDIBLE_API_KEY: 'xxxxxxxxxxxxxx'
```

**Comment by mbifulco** [comment]
Not sure why I never merged this.  Looks good - thanks!

**Pull request merged**
